version: '3.8'

services:
  app:
    container_name: consumables-app
    build: .
    ports:
      - "12345:5000"
    env_file:
      - .env
    command: ash -c "alembic upgrade head && gunicorn app.main:app -b 0.0.0.0:5000 --access-logfile - --error-logfile -"
    depends_on:
      - postgres
    networks:
      - consumables-network

  postgres:
    container_name: consumables-postgres
    image: postgres:16.0-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - consumables_app:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - consumables-network

volumes:
  consumables_app:

networks:
  consumables-network:
    driver: bridge
